name: CI
on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.3' 
    
    - run: pip install pytz
    
    - run: pip install requests

    - run: python main.py
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        STUDENTID: ${{ secrets.STUDENTID }}
          
